<?php

use frontend\models\Transducers2;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\grid\GridView;
use yii\widgets\Pjax;
/** @var yii\web\View $this */
/** @var frontend\models\Transducers2Search $searchModel */
/** @var yii\data\ActiveDataProvider $dataProvider */

$this->title = 'Transducers2s';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="transducers2-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Transducers2', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'DataSource:ntext',
            'Brand',
            'Model',
            'Type',
            //'Status',
            //'Dnom_in',
            //'Re',
            //'Fs',
            //'Qm',
            //'Qe',
            //'Qt',
            //'Rm',
            //'Mm',
            //'Cm',
            //'Vas',
            //'Sd',
            //'BL',
            //'Pe',
            //'Xmax',
            //'CreepBeta',
            //'Z1k',
            //'Z10k',
            //'L2',
            //'Le',
            //'Ke',
            //'R2',
            //'USPL',
            //'Beta',
            //'Revision',
            //'EntryDate',
            //'Vocc',
            //'MassOA',
            //'DiamOA',
            //'HeightOA',
            //'TargetCurve',
            //'TestSignal',
            //'Cost',
            //'URL:url',
            //'DataSheet',
            //'entered_by',
            //'DataDate',
            //'Km',
            //'Xmax_geom',
            //'Xmax_damage',
            //'n0',
            //'Vd',
            //'Res',
            //'Cmes',
            //'Lces',
            //'Dd',
            //'SPL1W',
            //'Depth',
            //'MotorH',
            //'MotorDiam',
            //'VCd',
            //'VCMass',
            //'Vocc_est',
            //'Vocc_rough',
            //'Dnom_cm',
            //'Znom',
            //'kLe',
            //'fLe',
            //'DiaphH',
            //'Df',
            //'fpist',
            //'f4pi',
            //'f2pi',
            //'fmax',
            //'Mair',
            //'Mmd',
            //'Zres',
            //'EBP',
            //'Gamma',
            //'Mpow',
            //'SPLmx',
            //'Hc',
            //'Hg',
            //'AspectR',
            //'LengthOA',
            //'WidthOA',
            //'F_HighRated',
            //'F_LowRated',
            //'VCMat',
            //'FormerMat',
            //'DiaphMat',
            //'SurrMat',
            //'SpidMat',
            //'FrameMat',
            //'MagMat',
            //'DiaphShape',
            //'MotorShape',
            //'MotorLength',
            //'MotorWidth',
            //'FlangeH',
            //'MagDiam',
            //'MagH',
            //'MagMass',
            //'Bpeak',
            //'BaffleCutoutDiam',
            //'BaffleCutoutLength',
            //'BaffleCutoutWidth',
            //'BoltCircleDiam',
            //'BoltCircleScrewDiam',
            //'BoltCircleScrewQty',
            //'TerminalPairsQty',
            //'TempLowPerfRated',
            //'TempHighPerfRated',
            //'TempLowDamageRated',
            //'TempHighDamageRated',
            //'HumidityLowPerfRated',
            //'HumidityHighPerfRated',
            //'HumidityLowDamageRated',
            //'HumidityHighDamageRated',
            //'Urms_100H_Max',
            //'Urms_Max_Rated',
            //'Pmax_Rated',
            //'BL1',
            //'BL2',
            //'BL3',
            //'BL4',
            //'BL5',
            //'BL6',
            //'BL7',
            //'BL8',
            //'K1',
            //'K2',
            //'K3',
            //'K4',
            //'K5',
            //'K6',
            //'K7',
            //'K8',
            //'Lx1',
            //'Lx2',
            //'Lx3',
            //'Lx4',
            //'Lx5',
            //'Lx6',
            //'Lx7',
            //'Lx8',
            //'Li1',
            //'Li2',
            //'Li3',
            //'Li4',
            //'Rmv1',
            //'Rmv2',
            //'Rmv3',
            //'Rmv4',
            //'Rtm',
            //'Rtv',
            //'tauC',
            //'tauM',
            //'Rv',
            //'AlphaBypass',
            //'Ctm',
            //'Ctv',
            //'DIY_Availability:ntext',
            //'Application:ntext',
            //'Notes:ntext',
            [
                'class' => ActionColumn::className(),
                'urlCreator' => function ($action, Transducers2 $model, $key, $index, $column) {
                    return Url::toRoute([$action, 'id' => $model->id]);
                 }
            ],
        ],
    ]); ?>

    <?php Pjax::end(); ?>

</div>
