<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/** @var yii\web\View $this */
/** @var frontend\models\Transducers2 $model */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Transducers2s', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="transducers2-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'DataSource:ntext',
            'Brand',
            'Model',
            'Type',
            'Status',
            'Dnom_in',
            'Re',
            'Fs',
            'Qm',
            'Qe',
            'Qt',
            'Rm',
            'Mm',
            'Cm',
            'Vas',
            'Sd',
            'BL',
            'Pe',
            'Xmax',
            'CreepBeta',
            'Z1k',
            'Z10k',
            'L2',
            'Le',
            'Ke',
            'R2',
            'USPL',
            'Beta',
            'Revision',
            'EntryDate',
            'Vocc',
            'MassOA',
            'DiamOA',
            'HeightOA',
            'TargetCurve',
            'TestSignal',
            'Cost',
            'URL:url',
            'DataSheet',
            'entered_by',
            'DataDate',
            'Km',
            'Xmax_geom',
            'Xmax_damage',
            'n0',
            'Vd',
            'Res',
            'Cmes',
            'Lces',
            'Dd',
            'SPL1W',
            'Depth',
            'MotorH',
            'MotorDiam',
            'VCd',
            'VCMass',
            'Vocc_est',
            'Vocc_rough',
            'Dnom_cm',
            'Znom',
            'kLe',
            'fLe',
            'DiaphH',
            'Df',
            'fpist',
            'f4pi',
            'f2pi',
            'fmax',
            'Mair',
            'Mmd',
            'Zres',
            'EBP',
            'Gamma',
            'Mpow',
            'SPLmx',
            'Hc',
            'Hg',
            'AspectR',
            'LengthOA',
            'WidthOA',
            'F_HighRated',
            'F_LowRated',
            'VCMat',
            'FormerMat',
            'DiaphMat',
            'SurrMat',
            'SpidMat',
            'FrameMat',
            'MagMat',
            'DiaphShape',
            'MotorShape',
            'MotorLength',
            'MotorWidth',
            'FlangeH',
            'MagDiam',
            'MagH',
            'MagMass',
            'Bpeak',
            'BaffleCutoutDiam',
            'BaffleCutoutLength',
            'BaffleCutoutWidth',
            'BoltCircleDiam',
            'BoltCircleScrewDiam',
            'BoltCircleScrewQty',
            'TerminalPairsQty',
            'TempLowPerfRated',
            'TempHighPerfRated',
            'TempLowDamageRated',
            'TempHighDamageRated',
            'HumidityLowPerfRated',
            'HumidityHighPerfRated',
            'HumidityLowDamageRated',
            'HumidityHighDamageRated',
            'Urms_100H_Max',
            'Urms_Max_Rated',
            'Pmax_Rated',
            'BL1',
            'BL2',
            'BL3',
            'BL4',
            'BL5',
            'BL6',
            'BL7',
            'BL8',
            'K1',
            'K2',
            'K3',
            'K4',
            'K5',
            'K6',
            'K7',
            'K8',
            'Lx1',
            'Lx2',
            'Lx3',
            'Lx4',
            'Lx5',
            'Lx6',
            'Lx7',
            'Lx8',
            'Li1',
            'Li2',
            'Li3',
            'Li4',
            'Rmv1',
            'Rmv2',
            'Rmv3',
            'Rmv4',
            'Rtm',
            'Rtv',
            'tauC',
            'tauM',
            'Rv',
            'AlphaBypass',
            'Ctm',
            'Ctv',
            'DIY_Availability:ntext',
            'Application:ntext',
            'Notes:ntext',
        ],
    ]) ?>

</div>
